# Generated by Django 6.0.1 on 2026-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类图标')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='副标题')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('specification', models.CharField(blank=True, max_length=100, null=True, verbose_name='规格')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='产地')),
                ('shelf_life', models.IntegerField(default=7, verbose_name='保质期(天)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='产品描述')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详细介绍')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/', verbose_name='封面图')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='产品图片')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales_count', models.IntegerField(default=0, verbose_name='销量')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_hot', models.BooleanField(default=False, verbose_name='热门推荐')),
                ('is_new', models.BooleanField(default=False, verbose_name='新品上市')),
                ('is_subscription', models.BooleanField(default=False, verbose_name='支持周期购')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'db_table': 'product_images',
                'ordering': ['sort_order'],
            },
        ),
    ]
