# Generated by Django 6.0.1 on 2026-01-27 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=20, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='delivery/avatars/', verbose_name='头像')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('vehicle_type', models.CharField(default='电动车', max_length=50, verbose_name='交通工具')),
                ('status', models.CharField(choices=[('active', '在岗'), ('inactive', '休息'), ('busy', '配送中')], default='active', max_length=20, verbose_name='状态')),
                ('delivery_area', models.TextField(blank=True, null=True, verbose_name='配送区域')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='总配送量')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '配送员',
                'verbose_name_plural': '配送员',
                'db_table': 'delivery_persons',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待配送'), ('picked', '已取货'), ('delivering', '配送中'), ('delivered', '已送达'), ('failed', '配送失败')], default='pending', max_length=20, verbose_name='配送状态')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货电话')),
                ('receiver_address', models.TextField(verbose_name='收货地址')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='取货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('customer_remark', models.TextField(blank=True, null=True, verbose_name='客户备注')),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='delivery.deliveryperson', verbose_name='配送员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '配送记录',
                'verbose_name_plural': '配送记录',
                'db_table': 'delivery_records',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='配送日期')),
                ('total_orders', models.IntegerField(default=0, verbose_name='订单数')),
                ('completed_orders', models.IntegerField(default=0, verbose_name='完成数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.deliveryperson', verbose_name='配送员')),
                ('records', models.ManyToManyField(related_name='route', to='delivery.deliveryrecord', verbose_name='配送记录')),
            ],
            options={
                'verbose_name': '配送路线',
                'verbose_name_plural': '配送路线',
                'db_table': 'delivery_routes',
                'unique_together': {('delivery_person', 'date')},
            },
        ),
    ]
