# Generated by Django 6.0.1 on 2026-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('selected', models.BooleanField(default=True, verbose_name='已选中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额')),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('shipped', '已发货'), ('delivered', '已送达'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunding', '退款中'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='订单状态')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收货电话')),
                ('receiver_address', models.TextField(verbose_name='收货地址')),
                ('delivery_type', models.CharField(default='express', max_length=20, verbose_name='配送方式')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='配送费')),
                ('is_subscription', models.BooleanField(default=False, verbose_name='周期购')),
                ('subscription_frequency', models.CharField(blank=True, max_length=50, null=True, verbose_name='配送频率')),
                ('subscription_periods', models.IntegerField(default=1, verbose_name='配送期数')),
                ('current_period', models.IntegerField(default=1, verbose_name='当前期数')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='订单备注')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_image', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=64, unique=True, verbose_name='支付流水号')),
                ('trade_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='第三方交易号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('sandbox', '沙箱测试')], max_length=20, verbose_name='支付方式')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'payments',
            },
        ),
    ]
