# Generated by Django 6.0.1 on 2026-01-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_add_express_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='快递公司代码')),
                ('name', models.CharField(max_length=50, verbose_name='快递公司名称')),
                ('app_id', models.CharField(blank=True, max_length=100, verbose_name='AppID')),
                ('app_key', models.CharField(blank=True, max_length=200, verbose_name='AppKey')),
                ('app_secret', models.CharField(blank=True, max_length=200, verbose_name='AppSecret')),
                ('customer_code', models.CharField(blank=True, max_length=100, verbose_name='客户编码/月结账号')),
                ('api_url', models.CharField(blank=True, max_length=200, verbose_name='API地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('sender_name', models.CharField(blank=True, max_length=50, verbose_name='发件人姓名')),
                ('sender_phone', models.CharField(blank=True, max_length=20, verbose_name='发件人电话')),
                ('sender_province', models.CharField(blank=True, max_length=50, verbose_name='发件省份')),
                ('sender_city', models.CharField(blank=True, max_length=50, verbose_name='发件城市')),
                ('sender_district', models.CharField(blank=True, max_length=50, verbose_name='发件区县')),
                ('sender_address', models.CharField(blank=True, max_length=200, verbose_name='发件详细地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '快递公司',
                'verbose_name_plural': '快递公司',
                'db_table': 'express_company',
            },
        ),
        migrations.CreateModel(
            name='ExpressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_no', models.CharField(db_index=True, max_length=50, verbose_name='快递单号')),
                ('status', models.CharField(choices=[('created', '已下单'), ('collected', '已揽收'), ('in_transit', '运输中'), ('delivering', '派送中'), ('signed', '已签收'), ('failed', '签收失败'), ('cancelled', '已取消')], default='created', max_length=20, verbose_name='物流状态')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='收件人电话')),
                ('receiver_province', models.CharField(blank=True, max_length=50, verbose_name='收件省份')),
                ('receiver_city', models.CharField(blank=True, max_length=50, verbose_name='收件城市')),
                ('receiver_district', models.CharField(blank=True, max_length=50, verbose_name='收件区县')),
                ('receiver_address', models.CharField(max_length=200, verbose_name='收件详细地址')),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='揽收时间')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签收时间')),
                ('express_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='express.expresscompany', verbose_name='快递公司')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_orders', to='orders.order', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '快递订单',
                'verbose_name_plural': '快递订单',
                'db_table': 'express_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpressTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='状态')),
                ('description', models.TextField(verbose_name='描述')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('express_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='express.expressorder', verbose_name='快递订单')),
            ],
            options={
                'verbose_name': '物流轨迹',
                'verbose_name_plural': '物流轨迹',
                'db_table': 'express_trace',
                'ordering': ['-time'],
            },
        ),
    ]
