# Generated by Django 6.0.1 on 2026-01-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorder',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='取件码'),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预约取件时间'),
        ),
    ]
