# Generated by Django 6.0.1 on 2026-01-27 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_initial'),
        ('products', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='优惠码')),
                ('name', models.CharField(max_length=100, verbose_name='券名称')),
                ('type', models.CharField(choices=[('discount', '折扣券'), ('amount', '满减券'), ('shipping', '免运费券')], max_length=20, verbose_name='券类型')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='折扣(%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消费')),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大优惠')),
                ('total_count', models.IntegerField(default=0, verbose_name='发放总量')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用')),
                ('per_user_limit', models.IntegerField(default=1, verbose_name='每人限领')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_all_products', models.BooleanField(default=True, verbose_name='全场通用')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '已停用'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='使用说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='products.category', verbose_name='适用分类')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='applicable_coupons', to='products.product', verbose_name='适用产品')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='活动名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='活动描述')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='coupons/banners/', verbose_name='活动横幅')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('coupons', models.ManyToManyField(related_name='activities', to='coupons.coupon', verbose_name='关联优惠券')),
            ],
            options={
                'verbose_name': '优惠券活动',
                'verbose_name_plural': '优惠券活动',
                'db_table': 'coupon_activities',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unused', '未使用'), ('used', '已使用'), ('expired', '已过期')], default='unused', max_length=20, verbose_name='状态')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupons.coupon', verbose_name='优惠券')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='orders.order', verbose_name='使用订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'db_table': 'user_coupons',
                'ordering': ['-received_at'],
            },
        ),
    ]
