# Generated by Django 6.0.1 on 2026-01-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='exchange_limit',
            field=models.IntegerField(default=0, verbose_name='兑换限量'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='exchanged_count',
            field=models.IntegerField(default=0, verbose_name='已兑换数量'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_exchangeable',
            field=models.BooleanField(default=False, verbose_name='可积分兑换'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='points_required',
            field=models.IntegerField(default=0, verbose_name='所需积分'),
        ),
    ]
