# Generated by Django 4.2 on 2026-01-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_no', models.CharField(max_length=32, unique=True, verbose_name='订阅编号')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_image', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品图片')),
                ('frequency', models.CharField(choices=[('daily', '每天'), ('weekly', '每周一次'), ('biweekly', '每两周一次'), ('monthly', '每月一次')], default='weekly', max_length=20, verbose_name='配送频率')),
                ('quantity', models.IntegerField(default=1, verbose_name='每次数量')),
                ('total_periods', models.IntegerField(default=12, verbose_name='总期数')),
                ('delivered_count', models.IntegerField(default=0, verbose_name='已配送期数')),
                ('period_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每期价格')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('receiver_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='收货人')),
                ('receiver_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='收货电话')),
                ('receiver_address', models.TextField(blank=True, null=True, verbose_name='收货地址')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('next_delivery_date', models.DateField(blank=True, null=True, verbose_name='下次配送日期')),
                ('status', models.CharField(choices=[('active', '配送中'), ('paused', '已暂停'), ('completed', '已完成'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='products.product', verbose_name='产品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '周期购订阅',
                'verbose_name_plural': '周期购订阅',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
