# Generated by Django 6.0.1 on 2026-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('suggestion', '功能建议'), ('complaint', '投诉反馈'), ('quality', '产品质量'), ('delivery', '配送问题'), ('other', '其他')], default='suggestion', max_length=20, verbose_name='反馈类型')),
                ('title', models.CharField(max_length=100, verbose_name='反馈标题')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='回复内容')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
