# Generated by Django 6.0.1 on 2026-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, verbose_name='评分')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='评论图片')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名评论')),
                ('is_approved', models.BooleanField(default=True, verbose_name='已审核')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='商家回复')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
                'db_table': 'comment_likes',
            },
        ),
    ]
