# Generated by Django 6.0.1 on 2026-01-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_level',
            field=models.CharField(choices=[('regular', '普通会员'), ('silver', '银卡会员'), ('gold', '金卡会员'), ('platinum', '铂金会员')], default='regular', max_length=20, verbose_name='会员等级'),
        ),
    ]
