# Generated by Django 6.0.1 on 2026-01-28 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
        ('users', '0003_user_birthday_user_gender_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', '获得'), ('spend', '消费'), ('expire', '过期'), ('adjust', '调整')], max_length=20, verbose_name='类型')),
                ('source', models.CharField(choices=[('order', '订单奖励'), ('exchange', '兑换优惠券'), ('sign', '签到'), ('activity', '活动奖励'), ('admin', '管理员调整'), ('refund', '退款返还')], max_length=20, verbose_name='来源')),
                ('points', models.IntegerField(verbose_name='积分变动')),
                ('balance', models.IntegerField(verbose_name='变动后余额')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_records', to='orders.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'db_table': 'points_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
