# Generated by Django 6.0.1 on 2026-01-29 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0005_add_wechat_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsrecord',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_records', to='subscriptions.subscription', verbose_name='关联订阅'),
        ),
        migrations.AlterField(
            model_name='pointsrecord',
            name='source',
            field=models.CharField(choices=[('order', '订单奖励'), ('subscription', '周期购奖励'), ('exchange', '兑换优惠券'), ('sign', '签到'), ('activity', '活动奖励'), ('admin', '管理员调整'), ('refund', '退款返还')], max_length=20, verbose_name='来源'),
        ),
    ]
