# Generated by Django 6.0.1 on 2026-01-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='广告标题')),
                ('image', models.ImageField(upload_to='ads/', verbose_name='广告图片')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='跳转链接')),
                ('link_type', models.CharField(default='none', max_length=20, verbose_name='链接类型')),
                ('link_id', models.IntegerField(blank=True, null=True, verbose_name='关联ID')),
                ('position', models.CharField(choices=[('home_banner', '首页轮播'), ('home_popup', '首页弹窗'), ('category_banner', '分类页轮播')], default='home_banner', max_length=30, verbose_name='展示位置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'db_table': 'advertisements',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('system', '系统通知'), ('promotion', '促销活动'), ('order', '订单通知'), ('new_product', '新品上市'), ('expiry_warning', '临期提醒')], default='system', max_length=20, verbose_name='消息类型')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/', verbose_name='消息图片')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='跳转链接')),
                ('is_global', models.BooleanField(default=True, verbose_name='全局消息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统消息',
                'verbose_name_plural': '系统消息',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.message', verbose_name='消息')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
                'db_table': 'user_messages',
            },
        ),
    ]
